import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = Path(__file__).resolve().parents[4]
INSTALL_ROOT = PROJECT_ROOT / "install"


def _logical_requirements(path: Path) -> list[str]:
    logical: list[str] = []
    pending: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        pending.append(line.removesuffix("\\").strip())
        if not line.endswith("\\"):
            logical.append(" ".join(pending))
            pending = []
    assert not pending, f"unterminated requirement in {path}"
    return logical


def test_python_release_baseline_is_311_everywhere():
    assert (PROJECT_ROOT / ".python-version").read_text(encoding="utf-8").strip() == "3.11"

    devbox = (PROJECT_ROOT / "devbox.json").read_text(encoding="utf-8")
    assert re.search(r'"python"\s*:\s*"3\.11"', devbox)


def test_requirement_sources_exist_and_layer_base_pi_and_dev():
    base = (INSTALL_ROOT / "requirements-base.in").read_text(encoding="utf-8")
    pi = (INSTALL_ROOT / "requirements-pi.in").read_text(encoding="utf-8")
    dev = (INSTALL_ROOT / "requirements-dev.in").read_text(encoding="utf-8")

    assert "flask" in base.lower()
    assert "-r requirements-base.in" in pi
    assert "inky" in pi.lower()
    assert "gpiozero" in pi.lower()
    assert "lgpio" in pi.lower()
    assert "rpi.gpio" in pi.lower()
    assert "-r requirements-base.in" in dev
    assert "pytest" in dev.lower()


def test_compiled_requirement_locks_are_self_contained_exact_and_hashed():
    for name in ("requirements-base.txt", "requirements.txt", "requirements-dev.txt"):
        path = INSTALL_ROOT / name
        text = path.read_text(encoding="utf-8")
        requirements = [
            line for line in _logical_requirements(path) if not line.startswith(("-", "--"))
        ]

        assert "pip-compile" in text, f"{name} is not generated by pip-compile"
        assert requirements, f"{name} contains no resolved distributions"
        assert all("==" in requirement for requirement in requirements), name
        assert all("--hash=sha256:" in requirement for requirement in requirements), name
        assert not any(" @ " in requirement for requirement in requirements), name
        assert not any(line.startswith("-r ") for line in _logical_requirements(path)), name


def test_local_environment_scripts_enforce_311_hashes_and_owned_cleanup():
    shell_runner = (PROJECT_ROOT / "scripts" / "venv.sh").read_text(encoding="utf-8")
    powershell_runner = (REPO_ROOT / "tools" / "run_inkypi_tests.ps1").read_text(
        encoding="utf-8"
    )

    assert "set -Eeuo pipefail" in shell_runner
    assert "Python 3.11" in shell_runner
    assert "--require-hashes" in shell_runner
    assert "PYTHONDONTWRITEBYTECODE" in powershell_runner
    assert "Python 3.11" in powershell_runner
    assert re.search(r"Remove-Item[^\n]+\$processTemp", powershell_runner)
    assert not re.search(r"Remove-Item[^\n]+\$tmpRoot", powershell_runner)


def test_ci_actions_are_sha_pinned_and_jobs_are_bounded():
    workflows = [REPO_ROOT / ".github/workflows/test.yml", REPO_ROOT / ".github/workflows/security.yml"]
    for workflow in workflows:
        text = workflow.read_text(encoding="utf-8")
        assert "permissions:\n  contents: read" in text
        assert "timeout-minutes:" in text
        action_refs = re.findall(r"^\s*-?\s*uses:\s*([^\s#]+)", text, flags=re.MULTILINE)
        assert action_refs, workflow.name
        for action_ref in action_refs:
            if action_ref.startswith("./"):
                continue
            assert re.search(r"@[0-9a-f]{40}$", action_ref), action_ref

    security = workflows[1].read_text(encoding="utf-8")
    assert "schedule:" in security
    assert "workflow_dispatch:" in security
    assert "run_simulated_soak.py --duration-seconds 1800" in security
    assert "--require-hashes --no-deps" in security
    assert "-r install/requirements.txt" in security
    assert "-r inkypi-weather/package/InkyPi/install/requirements.txt" in security
    assert security.count("python -m pip_audit") == 2
    assert (REPO_ROOT / "tools/run_simulated_soak.py").is_file()


def test_ci_whitespace_gate_checks_committed_changes():
    workflow = (REPO_ROOT / ".github/workflows/test.yml").read_text(encoding="utf-8")

    assert "fetch-depth: 0" in workflow
    assert "EVENT_BEFORE: ${{ github.event.before }}" in workflow
    assert 'GITHUB_BASE_REF' in workflow
    assert 'git diff --check "$base" HEAD' in workflow
    assert "run: git diff --check\n" not in workflow


def test_release_scripts_and_services_are_forced_to_lf():
    attributes = (REPO_ROOT / ".gitattributes").read_text(encoding="utf-8")
    assert "*.sh text eol=lf" in attributes
    assert "*.service text eol=lf" in attributes
    assert "*.socket text eol=lf" in attributes
    for relative in (
        "inkypi-weather/package/InkyPi/install/inkypi",
        "inkypi-weather/package/InkyPi/install/inkypi-update",
        "inkypi-weather/package/InkyPi/install/cli/inkypi-plugin",
        "inkypi-weather/package/InkyPi/install/debian-requirements.txt",
    ):
        assert f"{relative} text eol=lf" in attributes

    for relative in (
        "inkypi-weather/package/InkyPi/install/update_vendors.sh",
        "inkypi-weather/package/InkyPi/install/inkypi",
        "inkypi-weather/package/InkyPi/install/inkypi-update",
        "inkypi-weather/package/InkyPi/install/cli/inkypi-plugin",
        "inkypi-weather/package/InkyPi/install/debian-requirements.txt",
        "inkypi-weather/package/InkyPi/install/privileged/inkypi-privileged.socket",
    ):
        assert b"\r" not in (REPO_ROOT / relative).read_bytes()
    assert b"\r" not in (PROJECT_ROOT / "install/inkypi.service").read_bytes()


def test_operations_docs_use_the_supported_launcher_interface():
    troubleshooting = (PROJECT_ROOT / "docs/troubleshooting.md").read_text(encoding="utf-8")
    assert "inkypi -d" not in troubleshooting
    assert "/usr/local/inkypi/venv_inkypi" not in troubleshooting
    assert "/usr/local/bin/inkypi run" in troubleshooting


def test_gitleaks_exceptions_are_exact_historical_fingerprints():
    ignore_path = REPO_ROOT / ".gitleaksignore"
    entries = {
        line.strip()
        for line in ignore_path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    assert entries == {
        "3e33ff6441b6714a64abd3c936667e172c791150:inkypi-weather/package/InkyPi/src/plugins/sports_dashboard/common.py:generic-api-key:273",
        "74c362575e1471b568db22c0b7a1437f76820ced:tools/download_lck_team_logos.py:generic-api-key:17",
        "eee057a57bab0e1f23db191c31ccf08fd80d4c0b:inkypi-weather/package/InkyPi/src/plugins/sports_dashboard/sports_dashboard.py:generic-api-key:76",
    }
