"""Simplified-Chinese display names for the supported club leagues.

English provider names remain the canonical matching keys. Their league-scoped
registry IDs also group exact provider aliases during event reconciliation;
matching never depends on translated strings or raw provider IDs.

Rows that share a team ID are deliberate exact-name aliases from different
providers. Keep them explicit: broad prefix or year stripping can merge
unrelated clubs and would also weaken event reconciliation.
"""


CLUB_FOOTBALL_TEAM_LOCALIZATIONS = {
    "PL": (
        ("306", "Hull City", "赫尔城"),
        ("306", "Hull City AFC", "赫尔城"),
        ("331", "Brighton & Hove Albion", "布莱顿"),
        ("337", "Brentford", "布伦特福德"),
        ("349", "AFC Bournemouth", "伯恩茅斯"),
        ("357", "Leeds United", "利兹联"),
        ("359", "Arsenal", "阿森纳"),
        ("360", "Manchester United", "曼联"),
        ("361", "Newcastle United", "纽卡斯尔联"),
        ("362", "Aston Villa", "阿斯顿维拉"),
        ("363", "Chelsea", "切尔西"),
        ("364", "Liverpool", "利物浦"),
        ("366", "Sunderland", "桑德兰"),
        ("366", "Sunderland AFC", "桑德兰"),
        ("367", "Tottenham Hotspur", "热刺"),
        ("368", "Everton", "埃弗顿"),
        ("370", "Fulham", "富勒姆"),
        ("373", "Ipswich Town", "伊普斯维奇"),
        ("382", "Manchester City", "曼城"),
        ("384", "Crystal Palace", "水晶宫"),
        ("388", "Coventry City", "考文垂"),
        ("393", "Nottingham Forest", "诺丁汉森林"),
        ("371", "West Ham United", "西汉姆联"),
        ("380", "Wolverhampton Wanderers", "狼队"),
        ("379", "Burnley", "伯恩利"),
        ("375", "Leicester City", "莱斯特城"),
        ("376", "Southampton", "南安普顿"),
        ("381", "Norwich City", "诺维奇"),
        ("398", "Sheffield United", "谢菲尔德联"),
    ),
    "PD": (
        ("101", "Rayo Vallecano", "巴列卡诺"),
        ("101", "Rayo Vallecano de Madrid", "巴列卡诺"),
        ("102", "Villarreal", "比利亚雷亚尔"),
        ("1068", "Atletico Madrid", "马德里竞技"),
        ("1068", "Atlético Madrid", "马德里竞技"),
        ("1068", "Club Atlético de Madrid", "马德里竞技"),
        ("1538", "Levante", "莱万特"),
        ("1538", "Levante UD", "莱万特"),
        ("243", "Sevilla", "塞维利亚"),
        ("244", "Real Betis", "皇家贝蒂斯"),
        ("244", "Real Betis Balompié", "皇家贝蒂斯"),
        ("2922", "Getafe", "赫塔费"),
        ("3751", "Elche", "埃尔切"),
        ("83", "Barcelona", "巴塞罗那"),
        ("83", "FC Barcelona", "巴塞罗那"),
        ("85", "Celta Vigo", "塞尔塔"),
        ("85", "RC Celta de Vigo", "塞尔塔"),
        ("86", "Real Madrid", "皇家马德里"),
        ("87", "Racing Santander", "桑坦德竞技"),
        ("88", "Espanyol", "西班牙人"),
        ("88", "RCD Espanyol de Barcelona", "西班牙人"),
        ("89", "Real Sociedad", "皇家社会"),
        ("89", "Real Sociedad de Fútbol", "皇家社会"),
        ("90", "Deportivo La Coruña", "拉科鲁尼亚"),
        ("93", "Athletic Club", "毕尔巴鄂竞技"),
        ("94", "Valencia", "瓦伦西亚"),
        ("96", "Alavés", "阿拉维斯"),
        ("96", "Deportivo Alavés", "阿拉维斯"),
        ("97", "Osasuna", "奥萨苏纳"),
        ("97", "CA Osasuna", "奥萨苏纳"),
        ("99", "Málaga", "马拉加"),
        ("9812", "Girona", "赫罗纳"),
        ("2029", "Real Oviedo", "皇家奥维耶多"),
        ("84", "Mallorca", "马略卡"),
        ("84", "RCD Mallorca", "马略卡"),
        ("98", "Las Palmas", "拉斯帕尔马斯"),
    ),
    "BL1": (
        ("10388", "SV Elversberg", "埃尔弗斯贝格"),
        ("11420", "RB Leipzig", "RB莱比锡"),
        ("122", "FC Cologne", "科隆"),
        ("122", "1. FC Köln", "科隆"),
        ("124", "Borussia Dortmund", "多特蒙德"),
        ("125", "Eintracht Frankfurt", "法兰克福"),
        ("126", "SC Freiburg", "弗赖堡"),
        ("127", "Hamburg SV", "汉堡"),
        ("127", "Hamburger SV", "汉堡"),
        ("131", "Bayer Leverkusen", "勒沃库森"),
        ("131", "Bayer 04 Leverkusen", "勒沃库森"),
        ("132", "Bayern Munich", "拜仁慕尼黑"),
        ("132", "FC Bayern München", "拜仁慕尼黑"),
        ("133", "Schalke 04", "沙尔克04"),
        ("134", "VfB Stuttgart", "斯图加特"),
        ("137", "Werder Bremen", "云达不莱梅"),
        ("137", "SV Werder Bremen", "云达不莱梅"),
        ("268", "Borussia Mönchengladbach", "门兴格拉德巴赫"),
        ("2950", "Mainz", "美因茨"),
        ("2950", "1. FSV Mainz 05", "美因茨"),
        ("3307", "SC Paderborn 07", "帕德博恩"),
        ("3841", "FC Augsburg", "奥格斯堡"),
        ("598", "1. FC Union Berlin", "柏林联合"),
        ("7911", "TSG Hoffenheim", "霍芬海姆"),
        ("7911", "TSG 1899 Hoffenheim", "霍芬海姆"),
        ("138", "VfL Wolfsburg", "沃尔夫斯堡"),
        ("6418", "1. FC Heidenheim", "海登海姆"),
        ("6418", "1. FC Heidenheim 1846", "海登海姆"),
        ("270", "St. Pauli", "圣保利"),
        ("270", "FC St. Pauli 1910", "圣保利"),
        ("570", "Holstein Kiel", "荷尔斯泰因基尔"),
        ("121", "VfL Bochum", "波鸿"),
        ("123", "Darmstadt", "达姆施塔特"),
        ("129", "Hertha Berlin", "柏林赫塔"),
    ),
    "SA": (
        ("103", "AC Milan", "AC米兰"),
        ("104", "AS Roma", "罗马"),
        ("105", "Atalanta", "亚特兰大"),
        ("105", "Atalanta BC", "亚特兰大"),
        ("107", "Bologna", "博洛尼亚"),
        ("107", "Bologna FC 1909", "博洛尼亚"),
        ("109", "Fiorentina", "佛罗伦萨"),
        ("109", "ACF Fiorentina", "佛罗伦萨"),
        ("110", "Internazionale", "国际米兰"),
        ("110", "FC Internazionale Milano", "国际米兰"),
        ("111", "Juventus", "尤文图斯"),
        ("112", "Lazio", "拉齐奥"),
        ("112", "SS Lazio", "拉齐奥"),
        ("113", "Lecce", "莱切"),
        ("113", "US Lecce", "莱切"),
        ("114", "Napoli", "那不勒斯"),
        ("114", "SSC Napoli", "那不勒斯"),
        ("115", "Parma", "帕尔马"),
        ("115", "Parma Calcio 1913", "帕尔马"),
        ("118", "Udinese", "乌迪内斯"),
        ("17530", "Venezia", "威尼斯"),
        ("239", "Torino", "都灵"),
        ("2572", "Como", "科莫"),
        ("2572", "Como 1907", "科莫"),
        ("2925", "Cagliari", "卡利亚里"),
        ("3263", "Genoa", "热那亚"),
        ("3263", "Genoa CFC", "热那亚"),
        ("3997", "Sassuolo", "萨索洛"),
        ("3997", "US Sassuolo Calcio", "萨索洛"),
        ("4007", "Monza", "蒙扎"),
        ("4057", "Frosinone", "弗罗西诺内"),
        ("3956", "Pisa", "比萨"),
        ("3956", "AC Pisa 1909", "比萨"),
        ("4050", "Cremonese", "克雷莫内塞"),
        ("4050", "US Cremonese", "克雷莫内塞"),
        ("119", "Hellas Verona", "维罗纳"),
        ("2571", "Empoli", "恩波利"),
        ("4067", "Spezia", "斯佩齐亚"),
    ),
    "FL1": (
        ("160", "Paris Saint-Germain", "巴黎圣日耳曼"),
        ("166", "Lille", "里尔"),
        ("166", "Lille OSC", "里尔"),
        ("167", "Lyon", "里昂"),
        ("167", "Olympique Lyonnais", "里昂"),
        ("169", "Stade Rennais", "雷恩"),
        ("169", "Stade Rennais FC 1901", "雷恩"),
        ("170", "Troyes", "特鲁瓦"),
        ("170", "ES Troyes AC", "特鲁瓦"),
        ("172", "AJ Auxerre", "欧塞尔"),
        ("174", "AS Monaco", "摩纳哥"),
        ("175", "Lens", "朗斯"),
        ("175", "Racing Club de Lens", "朗斯"),
        ("176", "Marseille", "马赛"),
        ("176", "Olympique de Marseille", "马赛"),
        ("179", "Toulouse", "图卢兹"),
        ("180", "Strasbourg", "斯特拉斯堡"),
        ("180", "RC Strasbourg Alsace", "斯特拉斯堡"),
        ("2502", "Nice", "尼斯"),
        ("2502", "OGC Nice", "尼斯"),
        ("2697", "Le Mans", "勒芒"),
        ("273", "Lorient", "洛里昂"),
        ("273", "FC Lorient", "洛里昂"),
        ("3236", "Le Havre AC", "勒阿弗尔"),
        ("6851", "Paris FC", "巴黎FC"),
        ("6997", "Brest", "布雷斯特"),
        ("6997", "Stade Brestois 29", "布雷斯特"),
        ("7868", "Angers", "昂热"),
        ("7868", "Angers SCO", "昂热"),
        ("165", "Nantes", "南特"),
        ("165", "FC Nantes", "南特"),
        ("177", "Metz", "梅斯"),
        ("177", "FC Metz", "梅斯"),
        ("178", "Saint-Étienne", "圣埃蒂安"),
        ("274", "Montpellier", "蒙彼利埃"),
        ("3243", "Reims", "兰斯"),
        ("2011", "Caen", "卡昂"),
    ),
    "MLS": (
        ("18418", "Atlanta United FC", "亚特兰大联"),
        ("18418", "Atlanta United", "亚特兰大联"),
        ("20906", "Austin FC", "奥斯汀FC"),
        ("9720", "CF Montréal", "蒙特利尔CF"),
        ("9720", "CF Montreal", "蒙特利尔CF"),
        ("9720", "Montreal Impact", "蒙特利尔CF"),
        ("21300", "Charlotte FC", "夏洛特FC"),
        ("182", "Chicago Fire FC", "芝加哥火焰"),
        ("182", "Chicago Fire", "芝加哥火焰"),
        ("184", "Colorado Rapids", "科罗拉多急流"),
        ("183", "Columbus Crew", "哥伦布机员"),
        ("193", "D.C. United", "华盛顿联"),
        ("193", "DC United", "华盛顿联"),
        ("18267", "FC Cincinnati", "辛辛那提FC"),
        ("185", "FC Dallas", "达拉斯FC"),
        ("6077", "Houston Dynamo FC", "休斯敦迪纳摩"),
        ("6077", "Houston Dynamo", "休斯敦迪纳摩"),
        ("20232", "Inter Miami CF", "迈阿密国际"),
        ("20232", "Inter Miami", "迈阿密国际"),
        ("187", "LA Galaxy", "洛杉矶银河"),
        ("187", "Los Angeles Galaxy", "洛杉矶银河"),
        ("18966", "LAFC", "洛杉矶FC"),
        ("18966", "Los Angeles FC", "洛杉矶FC"),
        ("17362", "Minnesota United FC", "明尼苏达联"),
        ("17362", "Minnesota United", "明尼苏达联"),
        ("18986", "Nashville SC", "纳什维尔"),
        ("189", "New England Revolution", "新英格兰革命"),
        ("17606", "New York City FC", "纽约城"),
        ("17606", "NYCFC", "纽约城"),
        ("12011", "Orlando City SC", "奥兰多城"),
        ("10739", "Philadelphia Union", "费城联合"),
        ("9723", "Portland Timbers", "波特兰伐木者"),
        ("4771", "Real Salt Lake", "皇家盐湖城"),
        ("190", "Red Bull New York", "纽约红牛"),
        ("190", "New York Red Bulls", "纽约红牛"),
        ("190", "NY Red Bulls", "纽约红牛"),
        ("22529", "San Diego FC", "圣迭戈FC"),
        ("191", "San Jose Earthquakes", "圣何塞地震"),
        ("9726", "Seattle Sounders FC", "西雅图海湾人"),
        ("9726", "Seattle Sounders", "西雅图海湾人"),
        ("186", "Sporting Kansas City", "堪萨斯城竞技"),
        ("186", "Sporting KC", "堪萨斯城竞技"),
        ("21812", "St. Louis CITY SC", "圣路易斯城"),
        ("21812", "St. Louis City SC", "圣路易斯城"),
        ("21812", "St Louis CITY SC", "圣路易斯城"),
        ("7318", "Toronto FC", "多伦多FC"),
        ("9727", "Vancouver Whitecaps", "温哥华白帽"),
        ("9727", "Vancouver Whitecaps FC", "温哥华白帽"),
    ),
}


def contains_chinese(value):
    return any("\u3400" <= character <= "\u9fff" for character in str(value or ""))
