"""Additional ESPN college-football school identities, verified 2026-09-12.

IDs and aliases: ESPN 2026 FBS/FCS team catalogs and site team directory.
Chinese labels follow the dashboard convention: school, then team nickname.
Tuple fields: ESPN ID, code, short Chinese name, full Chinese name, aliases.
"""

NCAA_ADDITIONAL_SCHOOLS = (
    ("292", "RGV", "德州格兰德河谷", "德州格兰德河谷牛仔",
     ("UT Rio Grande Valley", "UT Rio Grande Valley Vaqueros", "UT Rio Grande", "UTRGV")),
    ('2000', 'ACU', '阿比林基督教', '阿比林基督教野猫',
     ('Abilene Christian', 'Abilene Chrstn', 'Abilene Christian Wildcats')),
    ('2010', 'AAMU', '阿拉巴马农工', '阿拉巴马农工斗牛犬',
     ('Alabama A&M', 'Alabama A&M Bulldogs')),
    ('2011', 'ALST', '阿拉巴马州立', '阿拉巴马州立黄蜂',
     ('Alabama State', 'Alabama St', 'Alabama State Hornets')),
    ('2016', 'ALCN', '奥尔康州立', '奥尔康州立勇士',
     ('Alcorn State', 'Alcorn St', 'Alcorn State Braves')),
    ('2032', 'ARST', '阿肯色州立', '阿肯色州立红狼',
     ('Arkansas State', 'Arkansas St', 'Arkansas State Red Wolves')),
    ('2029', 'UAPB', '阿肯色派恩布拉夫', '阿肯色派恩布拉夫金狮',
     ('Arkansas-Pine Bluff', 'AR-Pine Bluff', 'Arkansas-Pine Bluff Golden Lions')),
    ('2046', 'APSU', '奥斯汀佩伊', '奥斯汀佩伊州长',
     ('Austin Peay', 'Austin Peay Governors')),
    ('2065', 'BCU', '贝休恩库克曼', '贝休恩库克曼野猫',
     ('Bethune-Cookman', 'Bethune', 'Bethune-Cookman Wildcats')),
    ('225', 'BRWN', '布朗', '布朗熊',
     ('Brown', 'Brown Bears')),
    ('2803', 'BRY', '布莱恩特', '布莱恩特斗牛犬',
     ('Bryant', 'Bryant Bulldogs')),
    ('2083', 'BUCK', '巴克内尔', '巴克内尔野牛',
     ('Bucknell', 'Bucknell Bison')),
    ('2086', 'BTLR', '巴特勒', '巴特勒斗牛犬',
     ('Butler', 'Butler Bulldogs')),
    ('13', 'CP', '加州理工州立', '加州理工州立野马',
     ('Cal Poly', 'Cal Poly Mustangs')),
    ('2097', 'CAM', '坎贝尔', '坎贝尔战斗骆驼',
     ('Campbell', 'Campbell Fighting Camels')),
    ('2110', 'CARK', '中阿肯色', '中阿肯色熊',
     ('Central Arkansas', 'C Arkansas', 'Central Arkansas Bears')),
    ('2115', 'CCSU', '中康涅狄格州立', '中康涅狄格州立蓝魔',
     ('Central Connecticut', 'C Connecticut', 'Central Connecticut Blue Devils')),
    ('2127', 'CHSO', '查尔斯顿南方', '查尔斯顿南方海盗',
     ('Charleston Southern', 'Charleston So', 'Charleston Southern Buccaneers')),
    ('236', 'UTC', '田纳西查塔努加', '田纳西查塔努加知更鸟',
     ('Chattanooga', 'Chattanooga Mocs')),
    ('2130', 'CHST', '芝加哥州立', '芝加哥州立美洲狮',
     ('Chicago State', 'Chicago St', 'Chicago State Cougars')),
    ('2142', 'COLG', '科尔盖特', '科尔盖特突袭者',
     ('Colgate', 'Colgate Raiders')),
    ('171', 'COLU', '哥伦比亚', '哥伦比亚狮',
     ('Columbia', 'Columbia Lions')),
    ('172', 'COR', '康奈尔', '康奈尔大红',
     ('Cornell', 'Cornell Big Red')),
    ('159', 'DART', '达特茅斯', '达特茅斯大绿',
     ('Dartmouth', 'Dartmouth Big Green')),
    ('2166', 'DAV', '戴维森', '戴维森野猫',
     ('Davidson', 'Davidson Wildcats')),
    ('2168', 'DAY', '代顿', '代顿飞行者',
     ('Dayton', 'Dayton Flyers')),
    ('2169', 'DSU', '特拉华州立', '特拉华州立黄蜂',
     ('Delaware State', 'Delaware St', 'Delaware State Hornets')),
    ('2181', 'DRKE', '德雷克', '德雷克斗牛犬',
     ('Drake', 'Drake Bulldogs')),
    ('2184', 'DUQ', '杜肯', '杜肯公爵',
     ('Duquesne', 'Duquesne Dukes')),
    ('2193', 'ETSU', '东田纳西州立', '东田纳西州立海盗',
     ('East Tennessee State', 'ETSU', 'East Tennessee State Buccaneers')),
    ('2837', 'ETAM', '东德克萨斯农工', '东德克萨斯农工狮',
     ('East Texas A&M', 'East Texas A&M Lions', 'Texas A&M-Commerce', 'Texas A&M-Commerce Lions', 'TAMUC')),
    ('2197', 'EIU', '东伊利诺伊', '东伊利诺伊黑豹',
     ('Eastern Illinois', 'E Illinois', 'Eastern Illinois Panthers')),
    ('2198', 'EKU', '东肯塔基', '东肯塔基上校',
     ('Eastern Kentucky', 'E Kentucky', 'Eastern Kentucky Colonels')),
    ('331', 'EWU', '东华盛顿', '东华盛顿鹰',
     ('Eastern Washington', 'E Washington', 'Eastern Washington Eagles')),
    ('2210', 'ELON', '依隆', '依隆凤凰',
     ('Elon', 'Elon Phoenix')),
    ('50', 'FAMU', '佛罗里达农工', '佛罗里达农工响尾蛇',
     ('Florida A&M', 'Florida A&M Rattlers')),
    ('2230', 'FOR', '福特汉姆', '福特汉姆公羊',
     ('Fordham', 'Fordham Rams')),
    ('231', 'FUR', '弗尔曼', '弗尔曼圣骑士',
     ('Furman', 'Furman Paladins')),
    ('2241', 'GWEB', '加德纳韦伯', '加德纳韦伯奔跑斗牛犬',
     ('Gardner-Webb', "Gardner-Webb Runnin' Bulldogs")),
    ('46', 'GTWN', '乔治敦', '乔治敦霍亚',
     ('Georgetown', 'Georgetown Hoyas')),
    ('2755', 'GRAM', '格兰布林', '格兰布林老虎',
     ('Grambling', 'Grambling Tigers')),
    ('2261', 'HAMP', '汉普顿', '汉普顿海盗',
     ('Hampton', 'Hampton Pirates')),
    ('108', 'HARV', '哈佛', '哈佛绯红',
     ('Harvard', 'Harvard Crimson')),
    ('107', 'HC', '圣十字', '圣十字十字军',
     ('Holy Cross', 'Holy Cross Crusaders')),
    ('2277', 'HCU', '休斯敦基督教', '休斯敦基督教哈士奇',
     ('Houston Christian', 'Hou Christian', 'Houston Christian Huskies', 'Houston Baptist', 'Houston Baptist Huskies', 'HBU')),
    ('47', 'HOW', '霍华德', '霍华德野牛',
     ('Howard', 'Howard Bison')),
    ('304', 'IDST', '爱达荷州立', '爱达荷州立孟加拉虎',
     ('Idaho State', 'Idaho St', 'Idaho State Bengals')),
    ('70', 'IDHO', '爱达荷', '爱达荷汪达尔人',
     ('Idaho', 'Idaho Vandals')),
    ('2287', 'ILST', '伊利诺伊州立', '伊利诺伊州立红雀',
     ('Illinois State', 'Illinois St', 'Illinois State Redbirds')),
    ('2916', 'UIW', '圣道', '圣道红雀',
     ('Incarnate Word', 'Incarnate Word Cardinals')),
    ('282', 'INST', '印第安纳州立', '印第安纳州立悬铃木',
     ('Indiana State', 'Indiana St', 'Indiana State Sycamores')),
    ('2296', 'JKST', '杰克逊州立', '杰克逊州立老虎',
     ('Jackson State', 'Jackson St', 'Jackson State Tigers')),
    ('322', 'LAF', '拉法耶特', '拉法耶特豹',
     ('Lafayette', 'Lafayette Leopards')),
    ('2320', 'LAM', '拉马尔', '拉马尔红雀',
     ('Lamar', 'Lamar Cardinals')),
    ('2329', 'LEH', '里海', '里海山鹰',
     ('Lehigh', 'Lehigh Mountain Hawks')),
    ('2815', 'LIN', '林登伍德', '林登伍德狮',
     ('Lindenwood', 'Lindenwood Lions')),
    ('2341', 'LIU', '长岛', '长岛鲨鱼',
     ('Long Island University', 'Long Island', 'Long Island University Sharks')),
    ('311', 'ME', '缅因', '缅因黑熊',
     ('Maine', 'Maine Black Bears')),
    ('2368', 'MRST', '马里斯特', '马里斯特红狐',
     ('Marist', 'Marist Red Foxes')),
    ('113', 'MASS', '马萨诸塞', '马萨诸塞民兵',
     ('Massachusetts', 'UMass', 'Massachusetts Minutemen')),
    ('2377', 'MCN', '麦克尼斯', '麦克尼斯牛仔',
     ('McNeese', 'McNeese Cowboys')),
    ('2382', 'MER', '默瑟', '默瑟熊',
     ('Mercer', 'Mercer Bears')),
    ('2385', 'MERC', '梅西赫斯特', '梅西赫斯特湖人',
     ('Mercyhurst', 'Mercyhurst Lakers')),
    ('2771', 'MRMK', '梅里马克', '梅里马克勇士',
     ('Merrimack', 'Merrimack Warriors')),
    ('2393', 'MTSU', '中田纳西', '中田纳西蓝色突袭者',
     ('Middle Tennessee', 'MTSU', 'Middle Tennessee Blue Raiders')),
    ('2400', 'MVSU', '密西西比河谷州立', '密西西比河谷州立三角洲魔鬼',
     ('Mississippi Valley State', 'Miss Valley St', 'Mississippi Valley State Delta Devils')),
    ('2623', 'MOST', '密苏里州立', '密苏里州立熊',
     ('Missouri State', 'Missouri St', 'Missouri State Bears')),
    ('2405', 'MONM', '蒙茅斯', '蒙茅斯鹰',
     ('Monmouth', 'Monmouth Hawks')),
    ('149', 'MONT', '蒙大拿', '蒙大拿灰熊',
     ('Montana', 'Montana Grizzlies')),
    ('147', 'MTST', '蒙大拿州立', '蒙大拿州立山猫',
     ('Montana State', 'Montana St', 'Montana State Bobcats')),
    ('2413', 'MORE', '莫尔黑德州立', '莫尔黑德州立鹰',
     ('Morehead State', 'Morehead St', 'Morehead State Eagles')),
    ('2415', 'MORG', '摩根州立', '摩根州立熊',
     ('Morgan State', 'Morgan St', 'Morgan State Bears')),
    ('93', 'MUR', '默里州立', '默里州立赛马手',
     ('Murray State', 'Murray St', 'Murray State Racers')),
    ('160', 'UNH', '新罕布什尔', '新罕布什尔野猫',
     ('New Hampshire', 'New Hampshire Wildcats')),
    ('2441', 'NHVN', '纽黑文', '纽黑文冲锋者',
     ('New Haven', 'New Haven Chargers')),
    ('167', 'UNM', '新墨西哥', '新墨西哥狼',
     ('New Mexico', 'New Mexico Lobos')),
    ('2447', 'NICH', '尼科尔斯', '尼科尔斯上校',
     ('Nicholls', 'Nicholls Colonels')),
    ('2450', 'NORF', '诺福克州立', '诺福克州立斯巴达人',
     ('Norfolk State', 'Norfolk St', 'Norfolk State Spartans')),
    ('2453', 'UNA', '北阿拉巴马', '北阿拉巴马狮',
     ('North Alabama', 'North Alabama Lions')),
    ('2448', 'NCAT', '北卡罗来纳农工', '北卡罗来纳农工',
     ('North Carolina A&T', 'NC A&T', 'North Carolina A&T Aggies')),
    ('2428', 'NCCU', '北卡罗来纳中央', '北卡罗来纳中央鹰',
     ('North Carolina Central', 'NC Central', 'North Carolina Central Eagles')),
    ('155', 'UND', '北达科他', '北达科他战鹰',
     ('North Dakota', 'North Dakota Fighting Hawks')),
    ('2449', 'NDSU', '北达科他州立', '北达科他州立野牛',
     ('North Dakota State', 'N Dakota St', 'North Dakota State Bison')),
    ('249', 'UNT', '北德克萨斯', '北德克萨斯绿军',
     ('North Texas', 'North Texas Mean Green')),
    ('2464', 'NAU', '北亚利桑那', '北亚利桑那伐木工',
     ('Northern Arizona', 'N Arizona', 'Northern Arizona Lumberjacks')),
    ('2458', 'UNCO', '北科罗拉多', '北科罗拉多熊',
     ('Northern Colorado', 'N Colorado', 'Northern Colorado Bears')),
    ('2460', 'UNI', '北爱荷华', '北爱荷华黑豹',
     ('Northern Iowa', 'Northern Iowa Panthers')),
    ('2466', 'NWST', '西北州立', '西北州立魔鬼',
     ('Northwestern State', "N'Western St", 'Northwestern State Demons')),
    ('219', 'PENN', '宾夕法尼亚', '宾夕法尼亚贵格会',
     ('Pennsylvania', 'Penn', 'Pennsylvania Quakers')),
    ('2502', 'PRST', '波特兰州立', '波特兰州立维京人',
     ('Portland State', 'Portland St', 'Portland State Vikings')),
    ('2504', 'PV', '普雷里维尤农工', '普雷里维尤农工黑豹',
     ('Prairie View A&M', 'Prairie View', 'Prairie View A&M Panthers')),
    ('2506', 'PRES', '长老会学院', '长老会学院蓝袜',
     ('Presbyterian', 'Presbyterian Blue Hose')),
    ('163', 'PRIN', '普林斯顿', '普林斯顿老虎',
     ('Princeton', 'Princeton Tigers')),
    ('227', 'URI', '罗得岛', '罗得岛公羊',
     ('Rhode Island', 'Rhode Island Rams')),
    ('257', 'RICH', '里士满', '里士满蜘蛛',
     ('Richmond', 'Richmond Spiders')),
    ('2523', 'RMU', '罗伯特莫里斯', '罗伯特莫里斯殖民者',
     ('Robert Morris', 'Robert Morris Colonials')),
    ('2545', 'SELA', '东南路易斯安那', '东南路易斯安那狮',
     ('SE Louisiana', 'SE Louisiana Lions')),
    ('16', 'SAC', '萨克拉门托州立', '萨克拉门托州立黄蜂',
     ('Sacramento State', 'Sacramento St', 'Sacramento State Hornets')),
    ('2529', 'SHU', '圣心', '圣心先锋',
     ('Sacred Heart', 'Sacred Heart Pioneers')),
    ('2535', 'SAM', '桑福德', '桑福德斗牛犬',
     ('Samford', 'Samford Bulldogs')),
    ('301', 'USD', '圣迭戈', '圣迭戈斗牛士',
     ('San Diego', 'San Diego Toreros')),
    ('6', 'USA', '南阿拉巴马', '南阿拉巴马美洲虎',
     ('South Alabama', 'South Alabama Jaguars')),
    ('2569', 'SCST', '南卡罗来纳州立', '南卡罗来纳州立斗牛犬',
     ('South Carolina State', 'SC State', 'South Carolina State Bulldogs')),
    ('233', 'SDAK', '南达科他', '南达科他郊狼',
     ('South Dakota', 'South Dakota Coyotes')),
    ('2571', 'SDST', '南达科他州立', '南达科他州立长耳野兔',
     ('South Dakota State', 'S Dakota St', 'South Dakota State Jackrabbits')),
    ('2546', 'SEMO', '东南密苏里州立', '东南密苏里州立红鹰',
     ('Southeast Missouri State', 'SE Missouri', 'Southeast Missouri State Redhawks')),
    ('79', 'SIU', '南伊利诺伊', '南伊利诺伊萨路基猎犬',
     ('Southern Illinois', 'S Illinois', 'Southern Illinois Salukis')),
    ('2582', 'SOU', '南方大学', '南方大学美洲虎',
     ('Southern', 'Southern Jaguars')),
    ('253', 'SUU', '南犹他', '南犹他雷鸟',
     ('Southern Utah', 'Southern Utah Thunderbirds')),
    ('2900', 'STMN', '圣托马斯', '圣托马斯汤米',
     ('St. Thomas', 'St Thomas', 'St. Thomas Tommies')),
    ('2617', 'SFA', '斯蒂芬奥斯汀州立', '斯蒂芬奥斯汀州立伐木工',
     ('Stephen F. Austin', 'SF Austin', 'Stephen F. Austin Lumberjacks')),
    ('56', 'STET', '斯泰森', '斯泰森制帽人',
     ('Stetson', 'Stetson Hatters')),
    ('284', 'STO', '斯通希尔', '斯通希尔天鹰',
     ('Stonehill', 'Stonehill Skyhawks')),
    ('2619', 'STBK', '石溪', '石溪海狼',
     ('Stony Brook', 'Stony Brook Seawolves')),
    ('2627', 'TAR', '塔尔顿州立', '塔尔顿州立德州人',
     ('Tarleton State', 'Tarleton St', 'Tarleton State Texans')),
    ('2634', 'TNST', '田纳西州立', '田纳西州立老虎',
     ('Tennessee State', 'Tennessee St', 'Tennessee State Tigers')),
    ('2635', 'TNTC', '田纳西理工', '田纳西理工金鹰',
     ('Tennessee Tech', 'Tennessee Tech Golden Eagles')),
    ('245', 'TA&M', '德克萨斯农工', '德克萨斯农工',
     ('Texas A&M', 'Texas A&M Aggies', 'TAMU', 'Texas A and M')),
    ('2640', 'TXSO', '德克萨斯南方', '德克萨斯南方老虎',
     ('Texas Southern', 'Texas Southern Tigers')),
    ('326', 'TXST', '德克萨斯州立', '德克萨斯州立山猫',
     ('Texas State', 'Texas St', 'Texas State Bobcats')),
    ('2643', 'CIT', '城堡军事学院', '城堡军事学院斗牛犬',
     ('The Citadel', 'The Citadel Bulldogs')),
    ('119', 'TOW', '陶森', '陶森老虎',
     ('Towson', 'Towson Tigers')),
    ('5', 'UAB', '阿拉巴马伯明翰', '阿拉巴马伯明翰开拓者',
     ('UAB', 'UAB Blazers')),
    ('399', 'UALB', '奥尔巴尼', '奥尔巴尼大丹犬',
     ('UAlbany', 'UAlbany Great Danes')),
    ('302', 'UCD', '加州戴维斯', '加州戴维斯农工',
     ('UC Davis', 'UC Davis Aggies')),
    ('2433', 'ULM', '路易斯安那门罗', '路易斯安那门罗战鹰',
     ('UL Monroe', 'UL Monroe Warhawks')),
    ('2630', 'UTM', '田纳西马丁', '田纳西马丁天鹰',
     ('UT Martin', 'UT Martin Skyhawks')),
    ('3101', 'UTU', '犹他理工', '犹他理工开拓者',
     ('Utah Tech', 'Utah Tech Trailblazers', 'Dixie State', 'Dixie State Trailblazers', 'DIX')),
    ('2678', 'VMI', '弗吉尼亚军事学院', '弗吉尼亚军事学院军校生',
     ('VMI', 'VMI Keydets')),
    ('2674', 'VAL', '瓦尔帕莱索', '瓦尔帕莱索灯塔',
     ('Valparaiso', 'Valparaiso Beacons')),
    ('222', 'VILL', '维拉诺瓦', '维拉诺瓦野猫',
     ('Villanova', 'Villanova Wildcats')),
    ('2681', 'WAG', '瓦格纳', '瓦格纳海鹰',
     ('Wagner', 'Wagner Seahawks')),
    ('2692', 'WEB', '韦伯州立', '韦伯州立野猫',
     ('Weber State', 'Weber St', 'Weber State Wildcats')),
    ('110242', 'UWF', '西佛罗里达', '西佛罗里达阿尔戈英雄',
     ('West Florida', 'West Florida Argonauts')),
    ('2698', 'WGA', '西佐治亚', '西佐治亚狼',
     ('West Georgia', 'West Georgia Wolves')),
    ('2717', 'WCU', '西卡罗来纳', '西卡罗来纳山猫',
     ('Western Carolina', 'W Carolina', 'Western Carolina Catamounts')),
    ('2710', 'WIU', '西伊利诺伊', '西伊利诺伊陆战队',
     ('Western Illinois', 'W Illinois', 'Western Illinois Leathernecks')),
    ('2729', 'W&M', '威廉玛丽', '威廉玛丽部落',
     ('William & Mary', 'William & Mary Tribe')),
    ('2747', 'WOF', '沃福德', '沃福德梗犬',
     ('Wofford', 'Wofford Terriers')),
    ('43', 'YALE', '耶鲁', '耶鲁斗牛犬',
     ('Yale', 'Yale Bulldogs')),
    ('2754', 'YSU', '扬斯敦州立', '扬斯敦州立企鹅',
     ('Youngstown State', 'Youngstown St', 'Youngstown State Penguins')),
)
