export const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8DdTk9woDsaFcErjFJOF60tXtkJI
h6BvXpWnzY+W5LQHKtyaLhDvSaGvHU0i07N0g325SyepUgZRNFRoTgza2Q==
-----END PUBLIC KEY-----
`;
